					/* LOGICAL OPERATORS */
 -- AND OPERATOR (ALL THE CONDITION MUST BE TRUE)
 -- SQL TASK : RETRIEVE ALL CUSTOMERS WHO ARE FROM THE USA AND HAVE A SCORE GREATER THAN 150
 SELECT*							-- SELECTS ALL THE DATA
 From customers						-- FROM TABLE CUSTOMERS
 where								-- THIS IS OUR CONDITION (COUNTRY = USA and SCORE > 150)
 country = 'USA' AND score > 150

 -- OR OPERATOR (ATLEAST ONE CONDITION MUST BE TRUE)
 -- SQL TASK : RETRIEVE ALL CUSTOMERS WHO ARE EITHER FROM THE USA OR HAVE A SCORE GREATER THAN 150
 SELECT*
 FROM customers
 where 
 Country = 'USA' OR score > 150		-- THIS IS OUR CONDITION (COUNTRY = USA or SCORE > 150)

 -- NOT OPERATOR ( EXCLUDES MATCHING VALUES [REVERSE])
 -- SQL TASK: RETRIEVE ALL CUSTOMERS WITH A SCORE NOT LESS THAN 500
 SELECT *
 From customers
 where not score < 500			-- This is our condition ( score not less than 500 means score grater than 500)