-- RETREIVE ALL CUSTOMERS AND SORT THE RESULTS BY THE COUNTRY AND THEN BY THE HIGHEST SCORE.
use MyDatabase
SELECT *							--SELECTS ALL THE COLUMNS
FROM customers						-- FROM TABLE CUSTOMERS
ORDER BY country ASC, score DESC	-- SORTS THE DATA FROM COLUMN COUNTRY IN ASCENDING ORDER AND THEN SCORE in DESCENDING ORDER 