-- COMBINING DATA USING SET OPERATORS
--2. UNION ALL
--SQL TASK: COMBINE THE DATA FROM BOTH THE TABLE CUSTOMERS AND EMPLOYEE, INCLUDING DUPLICATES

use SalesDB			-- USE DATABASE SALESDB
SELECT				-- SELECTS THE COLUMNS SPECIFIED
FirstName
from sales.Customers;	-- FROM TABLE SALES.CUSTOMERS
UNION ALL-- UNION ALL RETURNS ALL THE DATA INCLUDING THE DUPLICATES FROM BOTH TABLE.
Select
FirstName
from sales.Employees;