-- COMBINING DATA USING SET OPERATORS
--1. UNION
--SQL TASK: COMBINE THE DATA FROM BOTH THE TABLE CUSTOMERS AND EMPLOYEE

use SalesDB			-- USE DATABASE SALESDB
SELECT				-- SELECTS THE COLUMNS SPECIFIED
FirstName
from sales.Customers;	-- FROM TABLE SALES.CUSTOMERS
UNION					-- UNION RETURNS ALL DISTINCT ROWS FROM BOTH QUERIES
Select
FirstName
from sales.Employees;

